"""Train the recommender and generate the website's ingredient list.

    python train.py --csv data/indian_food.csv
    python train.py --csv data/other.csv --name-col TranslatedRecipeName --ing-col Cleaned-Ingredients

Outputs
  artifacts/model.joblib                      - fitted model used by app.py
  artifacts/ingredients.json                  - ingredient list (name/category/icon/count)
  ../frontend/src/data/ingredients.js         - same list, ready for the React UI
"""
import argparse, json, math, os
from collections import Counter

import pandas as pd

from ingredient_meta import PANTRY, categorize, icon_for, split_ingredients
from recommender import Recommender

NAME_CANDIDATES = ["name", "recipe_name", "recipename", "translatedrecipename", "title", "dish", "dish_name"]
ING_CANDIDATES = ["ingredients", "cleaned-ingredients", "translatedingredients", "cleaned_ingredients",
                  "ingredient", "ner", "ingredients_list"]
META_CANDIDATES = ["diet", "prep_time", "cook_time", "flavor_profile", "course", "state", "region",
                   "cuisine", "totaltimeinmins", "servings", "url", "image-url"]
CATEGORY_ORDER = ["Vegetables", "Protein", "Dairy", "Grains", "Fruits", "Spices", "Other"]


def pick(cols, explicit, candidates, what):
    if explicit:
        if explicit not in cols:
            raise SystemExit(f"Column '{explicit}' not found. Columns: {list(cols)}")
        return explicit
    lowered = {c.lower(): c for c in cols}
    for c in candidates:
        if c in lowered:
            return lowered[c]
    raise SystemExit(f"Could not auto-detect the {what} column. Columns: {list(cols)}. Use --{what[:4]}-col.")


def clean_meta(row, cols):
    meta = {}
    for c in cols:
        v = row[c]
        if pd.isna(v) or str(v).strip() in ("", "-1", "-1.0"):
            continue
        meta[c.lower()] = v.item() if hasattr(v, "item") else v
    return meta


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True)
    ap.add_argument("--name-col"); ap.add_argument("--ing-col")
    ap.add_argument("--min-count", type=int, default=2, help="min #dishes an ingredient must appear in to be shown in the UI")
    ap.add_argument("--out-dir", default="artifacts")
    ap.add_argument("--frontend-file", default=os.path.join("..", "frontend", "src", "data", "ingredients.js"))
    a = ap.parse_args()

    df = pd.read_csv(a.csv)
    name_col = pick(df.columns, a.name_col, NAME_CANDIDATES, "name")
    ing_col = pick(df.columns, a.ing_col, ING_CANDIDATES, "ingredients")
    meta_cols = [c for c in df.columns if c.lower() in META_CANDIDATES]

    dishes = []
    for _, row in df.iterrows():
        ings = split_ingredients(row[ing_col])
        if len(ings) >= 2 and isinstance(row[name_col], str):
            dishes.append({"name": row[name_col].strip(), "ingredients": ings, "meta": clean_meta(row, meta_cols)})
    # drop exact-duplicate dish names (keep first)
    seen, unique = set(), []
    for d in dishes:
        k = d["name"].lower()
        if k not in seen:
            seen.add(k); unique.append(d)
    dishes = unique
    print(f"Loaded {len(dishes)} dishes from {a.csv} (name='{name_col}', ingredients='{ing_col}')")

    model = Recommender().fit(dishes)
    os.makedirs(a.out_dir, exist_ok=True)
    model.save(os.path.join(a.out_dir, "model.joblib"))

    # ---- ingredient list for the website --------------------------------
    counts = Counter(i for d in dishes for i in d["ingredients"])
    items = []
    for name, c in counts.items():
        if c >= a.min_count and name not in PANTRY:
            cat = categorize(name)
            items.append({"name": name.title(), "key": name, "category": cat, "icon": icon_for(name, cat), "count": c})
    items.sort(key=lambda x: (CATEGORY_ORDER.index(x["category"]), -x["count"], x["name"]))
    for n, it in enumerate(items, 1):
        it["id"] = n
    json.dump(items, open(os.path.join(a.out_dir, "ingredients.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)

    cats = ["All"] + [c for c in CATEGORY_ORDER if any(i["category"] == c for i in items)]
    os.makedirs(os.path.dirname(os.path.abspath(a.frontend_file)), exist_ok=True)
    with open(a.frontend_file, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by ml-service/train.py from the dataset - do not edit by hand.\n")
        f.write("export const CATEGORIES = " + json.dumps(cats, ensure_ascii=False) + ";\n\n")
        f.write("export const INGREDIENTS = [\n")
        for it in items:
            f.write("  " + json.dumps({k: it[k] for k in ("id", "name", "category", "icon")}, ensure_ascii=False) + ",\n")
        f.write("];\n")
    print(f"Wrote {len(items)} selectable ingredients -> {a.frontend_file}")
    print(f"Model saved -> {os.path.join(a.out_dir, 'model.joblib')}")


if __name__ == "__main__":
    main()
